#!/bin/bash

###
### SIGedge
###
###  20260827-1700
###
###
###  Usage:  SIGedge [ACTION] [TARGET|DEVICE]
###
###       ACTION
###
###          install                install TARGET from current release
###          remove                 remove installed TARGET
###          purge                  remove installed TARGET and purge configs
###          build                  compile and install TARGET (option may not be available)
###          package                compile only and copy packaged to SIG/debs directory (option may not be available)
###          menu                   Gtk Menu for SIGpi package management
###          update                 check for TARGET updates
###          upgrade                upgrade TARGET to latest release
###
###          device
###                 install         install DEVICE
###                 remove          remove DEVICE
###                 purge           purge DEVICE
###                 build           compile and install DEVICE (option may not be available)
###                 package         compile only and copy package to SIG/debs directory (option may not be available)
###
###          setup
###                 standard        First time setup for desktop
###                 server          First time setup for server
###                 apps            Manage applications (install/remove)
###
###          list
###                 packages        List all packages included with SIGpi
###                 installed       List installed SIGpi packages
###                 library         List all packages included with SIGpi with installed ones marked with an *
###
###          shell           provide SIGpi env variables around a TARGET
###
###       TARGET
###
###          A SIGpi package
###
###       DEVICE
###
###          A support SDR device
###


###
### INIT VARIABLES AND DIRECTORIES
###

# SIGedge directory tree
SIGEDGE_ENTRY="$(readlink -f "${BASH_SOURCE[0]}")"
SIGEDGE_HOME="$(cd -- "$(dirname -- "$SIGEDGE_ENTRY")" && pwd)"
SIGEDGE_ROOT=$SIGEDGE_HOME
SIGEDGE_SOURCE=$SIGEDGE_ROOT/source
SIGEDGE_ETC=$SIGEDGE_ROOT/etc
SIGEDGE_CONFIG=$SIGEDGE_ROOT/config
SIGEDGE_DEVICES=$SIGEDGE_HOME/devices
SIGEDGE_SCRIPTS=$SIGEDGE_HOME/scripts
SIGEDGE_PACKAGES=$SIGEDGE_HOME/packages
SIGEDGE_DEBS=$SIGEDGE_HOME/debs

# SIGedge install support files
SIGEDGE_INSTALLED=$SIGEDGE_ETC/INSTALLED_PKGS
SIGEDGE_PKGLIST=$SIGEDGE_PACKAGES/PACKAGES
SIGEDGE_INSTALLED_DEVICES=$SIGEDGE_ETC/INSTALLED_DEVICES
SIGEDGE_INSTALLED_SERVICES=$SIGEDGE_ETC/INSTALLED_SERVICES
SIGEDGE_DEVLIST=$SIGEDGE_DEVICES/DEVICES
SIGEDGE_SCREEN_STANDARD=$SIGEDGE_SCRIPTS/screen_standard_setup
SIGEDGE_SCREEN_SERVER=$SIGEDGE_SCRIPTS/screen_server_setup
SIGEDGE_BANNER_COLOR="\e[0;104m\e[K"   # blue
SIGEDGE_BANNER_RESET="\e[0m"

# Detect architecture (x86_64, ARMv8)
SIGEDGE_HWARCH=`lscpu|grep Architecture|awk '{print $2}'`
# Detect Operating system (Debian GNU/Linux 13 (Trixie) or Ubuntu 24.04 LTS)
SIGEDGE_OSNAME=`cat /etc/os-release|grep "PRETTY_NAME"|awk -F'"' '{print $2}'`
# Is Platform good for install- true or false - we start with false
SIGEDGE_CERTIFIED="false"
# What is the IP Address
SIGEDGE_IPADDR=`ip -br address | grep UP | awk '{print $1}'`


###
### FUNCTIONS
###

SIGEDGE_update(){
    # Check for available updates to package
    wget https://raw.githubusercontent.com/joecupano/SIGpi-edge/main/packages/PACKAGES -P $HOME/Downloads

    if grep $3 "$HOME/Downloads/PACKAGES"; then
        SIG_PKGSTAMP = 'grep $3 "$SIGEDGE_HOME/packages/PACKAGES"| cut -d,-f2'
        SIG_PKGNEW = 'grep $3 "$HOME/Downloads/PACKAGES"| cut -d,-f2'
        if [$SIG_PKGNEW != $SIG_PKGSTAMP]; then
            echo "Update $SIG_PKGNEW is available"
        else
            echo "No updates available"
        fi
    fi
}

SIGEDGE_upgrade(){
    # Remove Package, update local clone, install updated package
    cd $SIGEDGE_HOME
    source $SIGEDGE_PACKAGES/$SPKGSCRIPT remove
    git pull
    source $SIGEDGE_PACKAGES/$SPKGSCRIPT install
}

###
###  MAIN
###

ACTION=$1
SPACKAGE=$2
SPKGSCRIPT="pkg_$2"
SCFGSCRIPT="cfg_$2"

if [ "$1" = "device" ]; then
    SPKGSCRIPT="pkg_$3"
fi

case "$1" in
    setup )
        if [ "$2" = "apps" ]; then
            source $SIGEDGE_SCRIPTS/setup_apps
        elif [ "$2" = "" ]; then
            source $SIGEDGE_SCRIPTS/setup_start $2
        fi
        ;;

    list )
        if [ "$2" = "installed" ]; then
            echo " "
            echo -e "${SIGEDGE_BANNER_COLOR} ##"
            echo -e "${SIGEDGE_BANNER_COLOR} ##  SIGEDGE list installed"
            echo -e "${SIGEDGE_BANNER_COLOR} ##"
            echo -e "${SIGEDGE_BANNER_RESET}"
            echo " "
            echo -e "INSTALLED\t PACKAGE\t VERSION\t DESCRIPTION"
            echo " "
            awk 'BEGIN {FS=","} {printf "%-15s %-15s %-15s\n", $1, $2, $3}' $SIGEDGE_INSTALLED|more
        fi

        if [ "$2" = "packages" ]; then
            echo " "
            echo -e "${SIGEDGE_BANNER_COLOR} ##"
            echo -e "${SIGEDGE_BANNER_COLOR} ##  SIGEDGE list packages"
            echo -e "${SIGEDGE_BANNER_COLOR} ##"
            echo -e "${SIGEDGE_BANNER_RESET}"
            echo " "
            echo -e "PACKAGE\t VERSION\t DESCRIPTION"
            echo " "
            awk 'BEGIN {FS=","} {printf "%-15s %-15s %-15s\n", $1, $2, $3}' $SIGEDGE_PKGLIST|more
        fi

        if [ "$2" = "library" ]; then
                file1=$SIGEDGE_PKGLIST
                file2=$SIGEDGE_INSTALLED
                echo " "
                echo -e "${SIGEDGE_BANNER_COLOR} ##"
                echo -e "${SIGEDGE_BANNER_COLOR} ##  SIGEDGE list library"
                echo -e "${SIGEDGE_BANNER_COLOR} ##"
                echo -e "${SIGEDGE_BANNER_RESET}"
                echo " "
                echo -e "\tINSTALLED\t PACKAGE\t VERSION\t DESCRIPTION"
                while IFS= read -r line_file1
                do
                        if grep -qF "$line_file1" "$file2"; then
                                echo -e "*\t $line_file1"|awk 'BEGIN {FS=","} {printf "%-15s %-15s %-15s %-15s\n", " ", $1, $2, $3}'
                        else
                                echo -e " \t $line_file1"|awk 'BEGIN {FS=","} {printf "%-15s %-15s %-15s %-15s\n", " ", $1, $2, $3}'
                        fi
                done < "$file1"
        fi
        ;;

    build )
        source $SIGEDGE_PACKAGES/$SPKGSCRIPT build
        #sudo dpkg -i $SIGEDGE_DEBS/$2
        ;;

    package )
        source $SIGEDGE_PACKAGES/$SPKGSCRIPT package
        ;;

    remove )
        source $SIGEDGE_PACKAGES/$SPKGSCRIPT remove
        ;;

    purge )
        source $SIGEDGE_PACKAGES/$SPKGSCRIPT purge
        ;;

    install )
        source $SIGEDGE_PACKAGES/$SPKGSCRIPT install
        ;;

    menu )
        "$SIGEDGE_SCRIPTS/SIGEDGE_pkg_menu.py"
        ;;

    config )
        source $SIGEDGE_SCRIPTS/$SCFGSCRIPT $3
        ;;

    update )
        SIGEDGE_update $3
        ;;###

    upgrade)
        SIGEDGE_upgrade $3
        ;;

    device )
        case "$2" in
            build )
                source $SIGEDGE_DEVICES/$SPKGSCRIPT build
                ;;

            package )
                source $SIGEDGE_DEVICES/$SPKGSCRIPT package
                ;;

            remove )
                source $SIGEDGE_DEVICES/$SPKGSCRIPT remove
                ;;

            purge )
                source $SIGEDGE_DEVICES/$SPKGSCRIPT purge
                ;;

            install )
                source $SIGEDGE_DEVICES/$SPKGSCRIPT install
                ;;
        esac
        ;;

    shell )
        source $2
        ;;

    * )
        cat <<EOF

       Usage:  SIGpi [ACTION] [TARGET|DEVICE]

       ACTION

          install                install TARGET from current release
          remove                 remove installed TARGET
          purge                  remove installed TARGET and purge configs
          build                  compile and install TARGET (option may not be available)
          package                compile only and copy packaged to SIG/debs directory (option may not be available)
          menu                   Gtk Menu for pSIGpi package management
          update                 check for TARGET updates
          upgrade                upgrade TARGET to latest release

          device
                 install         install DEVICE
                 remove          remove DEVICE
                 purge           purge DEVICE
                 build           compile and install DEVICE (option may not be available)
                 package         compile only and copy package to SIG/debs directory (option may not be available)

          setup
                 standard        First time setup for desktop
                 server          First time setup for server
                 apps            Manage applications (install/remove)

          list
                 packages        List all packages included with SIGpi
                 installed       List installed SIGpi packages
                 library         List all packages included with SIGpi with installed ones marked with an *

          shell           provide SIGpi env variables around a TARGET

       TARGET

          A SIGpi package

       DEVICE

          A support SDR device

EOF
;;
esac

exit 0
