#!/bin/bash

###
### SIGpi
###
### pkg_bladerf
###
###
### 20260117-2300
###
### Nuand bladeRF and SoapyBladeRF
###

if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
    echo -e "${SIGEDGE_BANNER_COLOR}"
    echo -e "${SIGEDGE_BANNER_COLOR} ##  ERROR: Unknown action or package"
    echo -e "${SIGEDGE_BANNER_RESET}"
    exit 1
fi

case "$1" in
    remove|purge|install|build|package )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##  $1 : BladeRF"
        echo -e "${SIGEDGE_BANNER_RESET}"
        ;;&

    remove|purge )
        sudo apt-get remove -y bladerf bladerf-firmware bladerf-fpga

        cd $SIGEDGE_SOURCE/bladeRF/build/host
        sudo make uninstall
        sudo ldconfig
        cd $SIGEDGE_SOURCE
	    rm -rf $SIGEDGE_SOURCE/bladeRF
        sed -i /bladerf/d $SIGEDGE_INSTALLED_DEVICES

	    cd $SIGEDGE_SOURCE/SoapyBladeRF/build
        sudo make uninstall
        sudo ldconfig
        cd $SIGEDGE_SOURCE
        rm -rf $SIGEDGE_SOURCE/SoapyBladeRF
        rm -rf $HOME/.config/bladerf
        sudo rm -rf $SIGEDGE_DESKTOP/bladerf.desktop
        sudo rm -rf $DESKTOP_FILES/bladerf.desktop
        sed -i /SoapyBladeRF/d $SIGEDGE_INSTALLED_DEVICES
        ;;&

    install|build|package )
        ## DEPENDENCIES
        sudo apt-get install -y python3-six python3-mako python3-lxml
        sudo apt-get install -y python3-numpy python3-numpy python3-pip python3-pybind11 libsndfile1-dev
        ;;&

    install )
        ## REPO
        sudo add-apt-repository -y ppa:nuandllc/bladerf
        sudo apt update

        ## PACKAGE
        sudo apt-get install -y bladerf libbladerf-dev
        cat $SIGEDGE_DEVLIST|grep "bladerf" >> $SIGEDGE_INSTALLED_DEVICES

        ### SoapyBladeRF
        cd $SIGEDGE_SOURCE
        git clone https://github.com/pothosware/SoapyBladeRF.git
        cd SoapyBladeRF
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4
        sudo make install
        sudo ldconfig
        ;;&

    build )
        ## DEPENDENCIES
        sudo apt-get install -y python3-six python3-mako python3-lxml python3-numpy
        sudo apt-get install -y python3-pip git python3-pybind11 libsndfile1-dev
        ## PACKAGE

        ### BladeRF
        cd $SIGEDGE_SOURCE
        git clone --depth 1 https://github.com/Nuand/bladeRF.git
        cd bladeRF/host
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4
        sudo make install
        sudo ldconfig
        cat $SIGEDGE_DEVLIST|grep "bladerf" >> $SIGEDGE_INSTALLED_DEVICES

        ### SoapyBladeRF
        cd $SIGEDGE_SOURCE
        git clone https://github.com/pothosware/SoapyBladeRF.git
        cd SoapyBladeRF
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4
        sudo make install
        ;;&

    package )
        ## PACKAGE

        ### BladeRF
        cd $SIGEDGE_SOURCE
        git clone --depth 1 https://github.com/Nuand/bladeRF.git
        cd bladeRF/host
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4
        sudo checkinstall --install=no
        sudo mv *.deb $SIGEDGE_DEBS

        ### SoapyBladeRF
        cd $SIGEDGE_SOURCE
        git clone https://github.com/pothosware/SoapyBladeRF.git
        cd SoapyBladeRF
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4
        sudo checkinstall --install=no
	    sudo mv *.deb $SIGEDGE_DEBS
        ;;&

    remove|purge|install|build|package )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##  $1 : BladeRF - Completed"
        echo -e "${SIGEDGE_BANNER_RESET}"
        ;;
esac
