#!/bin/bash

###
### SIGpi
###
### pkg_ettus
###
###
### 20260117-2300
###
### Ettus Research USRP Devices
###

case "$1" in

    remove|purge|install|build|package )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##  $1 : Ettus Research USRP Devices"
        echo -e "${SIGEDGE_BANNER_RESET}"
        ;;&

    remove )
        sudo dpkg -r uhd
        sed -i /uhd/d $SIGEDGE_INSTALLED_DEVICES
        ;;&

    purge )
        sudo dpkg -P uhd
        sed -i /uhd/d $SIGEDGE_INSTALLED_DEVICES
        sudo rm -rf $SIGEDGE_SOURCE/uhd*
        ;;&

    install|build|package )
        ## DEPENDENCIES
        sudo apt-get install -y libboost-all-dev
        sudo apt-get install -y libusb-1.0-0-dev
        sudo apt-get install -y python3-mako
        ;;&

    install )
        ## PACKAGE
        cd $SIGEDGE_PACKAGES
        if [[ "$SIGEDGE_HWARCH" == "x86_64" ]]; then
	        cd $SIGEDGE_DEBS
	        sudo dpkg -i uhd_current_amd64.deb
            cat $SIGEDGE_DEVLIST|grep "ettus" >> $SIGEDGE_INSTALLED_DEVICES
        fi

        if [[ "$SIGEDGE_HWARCH" == "aarch64" ]]; then
            echo -e "${SIGEDGE_BANNER_COLOR}"
            echo -e "${SIGEDGE_BANNER_COLOR} ##  $1 : not available for aarch64"
            echo -e "${SIGEDGE_BANNER_RESET}"
            exit
        fi
        ;;&

    build|package )
        if [[ "$SIGEDGE_HWARCH" == "aarch64" ]]; then
            echo -e "${SIGEDGE_BANNER_COLOR}"
            echo -e "${SIGEDGE_BANNER_COLOR} ##  $1 : not available for aarch64"
            echo -e "${SIGEDGE_BANNER_RESET}"
            exit
        fi

        ## PACKAGE
        cd $SIGEDGE_SOURCE
        git clone https://github.com/EttusResearch/uhd.git
        cd uhd
        git checkout v4.9.0.1
        cd host
        mkdir build	&& cd build
        cmake .. -Wno-dev
        make -j4
        ;;&

    build )
        sudo make install
        sudo cp /usr/local/lib/uhd/utils/uhd-usrp.rules /etc/udev/rules.d/
        sudo ldconfig
        sudo uhd_images_downloader
        cat $SIGEDGE_DEVLIST|grep "ettus" >> $SIGEDGE_INSTALLED_DEVICES
        ;;&

    package )
        sudo checkinstall --install=no
        sudo mv *.deb $SIGEDGE_DEBS
        ;;&

    install|build|package|remove|purge )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##  $1 : Ettus Research USRP Devices completed"
        echo -e "${SIGEDGE_BANNER_RESET}"
        ;;&
esac