#!/bin/bash

###
### SIGPI
###
### pkg_hackrf
###
###
### 20260117-2300
###
### HackRF
###

if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
    echo -e "${SIGEDGE_BANNER_COLOR}"
    echo -e "${SIGEDGE_BANNER_COLOR} ##  ERROR: Unknown action or package"
    echo -e "${SIGEDGE_BANNER_RESET}"
    exit 1
fi

case "$1" in
    remove|purge|install|build|package )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##  $1 : HackRF"
        echo -e "${SIGEDGE_BANNER_RESET}"
        ;;&

    remove|purge )
       cd $SIGEDGE_SOURCE/hackrf/host/build
        sudo make uninstall
        sudo ldconfig
        cd $SIGEDGE_SOURCE
	    rm -rf $SIGEDGE_SOURCE/hackrf
        sed -i /hackrf/d $SIGEDGE_INSTALLED_DEVICES
	    ;;&

    install|build|package)
        ## DEPENDENCIES
        sudo apt-get install -y libusb-1.0-0-dev libfftw3-dev
        ;;&

    install|build )
        ## INSTALL
        cd $SIGEDGE_SOURCE
        git clone https://github.com/mossmann/hackrf.git
        cd hackrf/host
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4
        sudo make install
        sudo ldconfig

        cd $SIGEDGE_SOURCE
        git clone https://github.com/pothosware/SoapyHackRF.git
        cd SoapyHackRF
        mkdir build && cd build
        cmake .. -Wno-dev -DCMAKE_BUILD_TYPE=Release
        make -j4
        sudo make install
        sudo ldconfig
        cat $SIGEDGE_DEVLIST|grep "hackrf" >> $SIGEDGE_INSTALLED_DEVICES
        ;;&

     package )
        ## INSTALL
        cd $SIGEDGE_SOURCE
        git clone https://github.com/mossmann/hackrf.git
        cd hackrf/host
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4
        sudo checkinstall --install=no
        sudo mv *.deb $SIGEDGE_DEBS

        cd $SIGEDGE_SOURCE
        git clone https://github.com/pothosware/SoapyHackRF.git
        cd SoapyHackRF
        mkdir build && cd build
        cmake .. -Wno-dev -DCMAKE_BUILD_TYPE=Release
        make -j4
        sudo checkinstall --install=no
        sudo mv *.deb $SIGEDGE_DEBS
        ;;&

    remove|purge|install|build|package )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##  $1 : HackRF - Completed"
        echo -e "${SIGEDGE_BANNER_RESET}"
        ;;
esac