#!/bin/bash

###
### SIGpi
###
### pkg_libmirisdr
###
###
### 202601125-2300
###
###
### open-source driver specifically designed for SDR devices
### built on the Mirics MSi001 + MSi2500 chipset. This includes:
###
### - SDRplay RSP1
### - MSI-SDR / "M3" Receivers (RSP1 clones)
### - Mirics MSi2500 default dongles
### - Hauppauge WinTV 133559 LF: A specific TV tuner model
### - AverMedia A859 Pure DVBT:
###

case "$1" in
    remove|purge|install|build|package )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##   $1 : libmirisdr"
        echo -e "${SIGEDGE_BANNER_RESET}"
        ;;&

    remove )
        cd $SIGEDGE_DEBS
        sudo dpkg -r libmirisdr
        sudo dpkg -r soapymirisdr
        sed -i /libmirisdr/d $SIGEDGE_INSTALLED_DEVICES
        sed -i /soapymirisdr/d $SIGEDGE_INSTALLED_DEVICES
        ;;&

    purge )
        cd $SIGEDGE_DEBS
        sudo dpkg -P libmirisdr
        sudo dpkg -P soapymirisdr
        sed -i /libmirisdr/d $SIGEDGE_INSTALLED_DEVICES
        sed -i /soapymirisdr/d $SIGEDGE_INSTALLED_DEVICES
        ;;&

    install )
        ## PACKAGE
        cd $SIGEDGE_PACKAGES
        if [[ "$SIGEDGE_HWARCH" == "x86_64" ]]; then
	        cd $SIGEDGE_DEBS
	        sudo dpkg -i libmirisdr_current_amd64.deb
            sudo dpkg -i soapymirisdr_current_amd64.deb
        fi

        if [[ "$SIGEDGE_HWARCH" == "aarch64" ]]; then
	        cd $SIGEDGE_DEBS
            sudo dpkg -i libmirisdr_current_arm64.deb
            sudo dpkg -i soapymirisdr_current_arm64.deb
        fi
        cat $SIGEDGE_DEVLIST|grep "libmirisdr" >> $SIGEDGE_INSTALLED_DEVICES
        cat $SIGEDGE_DEVLIST|grep "soapymirisdr" >> $SIGEDGE_INSTALLED_DEVICES
        ;;&

    build|package )
        # Remove Kernel Drivers
        sudo modprobe -r msi2500 msi001
        sudo cp $SIGEDGE_CONFIG/blacklist-msi.conf /etc/modprobe.d/blacklist-msi.conf

        ## SDRplay driver
        cd $SIGEDGE_SOURCE
        git clone https://github.com/ericek111/libmirisdr-5
        cd libmirisdr-5
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4

        ## SoapySDRplay Driver
        cd $SIGEDGE_SOURCE
        git clone https://github.com/ericek111/SoapyMiri
        cd SoapyMiri
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4
        ;;&

    build )
        cd $SIGEDGE_SOURCE/libmirisdr-5/build
        sudo make install
        sudo ldconfig

        cd $SIGEDGE_SOURCE/SoapyMiri/build
        sudo make install
        sudo ldconfig
        cat $SIGEDGE_DEVLIST|grep "libmirisdr" >> $SIGEDGE_INSTALLED_DEVICES
        ;;&

    package)
        cd $SIGEDGE_SOURCE/libmirisdr-5/build
        sudo checkinstall --install=no
        sudo mv *.deb $SIGEDGE_DEBS

        cd $SIGEDGE_SOURCE/SoapyMiri/build
        sudo checkinstall --install=no
        sudo mv *.deb $SIGEDGE_DEBS
        ;;&

    remove|purge|install|build|package)
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##   $1 : Libmirisdr completed"
        echo -e "${SIGEDGE_BANNER_RESET}"
        ;;&

    * )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##  ERROR: Unkown action or package"
        echo -e "${SIGEDGE_BANNER_RESET}"
        ;;
esac