#!/bin/bash

###
### SIGpi
###
### pkg_limesuite
###
###
### 20260110-2300
###
### LimeSDR Devices
###

if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
    echo -e "${SIGEDGE_BANNER_COLOR}"
    echo -e "${SIGEDGE_BANNER_COLOR} ##  ERROR: Unknown action or package"
    echo -e "${SIGEDGE_BANNER_RESET}"
    exit 1
fi

case "$1" in
    remove|purge|install|build|package )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##  $1 : LimeSDR Devices"
        echo -e "${SIGEDGE_BANNER_RESET}"
        ;;&

    remove|purge )
        cd $SIGEDGE_SOURCE/LimeSuite/build-dir
        sudo make uninstall
        sudo ldconfig
        cd $SIGEDGE_SOURCE
	    rm -rf $SIGEDGE_SOURCE/LimeSuite
        sed -i /limesuite/d $SIGEDGE_INSTALLED_DEVICES

	    # Remove Menu icon
        sudo rm $SIGEDGE_DESKTOP_ICONS/LimeSuite.png
        # Remove Desktop links
        sudo rm $SIGEDGE_DESKTOP_FILES/LimeSuite.desktop
        ;;&

    install|build|package )
        ## DEPENDENCIES
        sudo apt-get install -y swig
        sudo apt-get install -y libsqlite3-dev
        sudo apt-get install -y libi2c-dev
        sudo apt-get install -y libusb-1.0-0-dev
        sudo apt-get install -y liboctave-dev
        sudo apt-get install -y libfltk1.3-dev
        sudo apt-get install -y libwxgtk3.0-gtk3-dev
        sudo apt-get install -y freeglut3-dev
        ;;&

    install )
        ## REPO
        sudo add-apt-repository -y ppa:myriadrf/drivers
        sudo apt-get update

        ## PACKAGE
        sudo apt-get install -y limesuite liblimesuite-dev limesuite-udev limesuite

        ## DESKTOP
        # Add Icon
        #sudo cp $SIGEDGE_SOURCE/LimeSuite/Desktop/*png $DESKTOP_ICONS
        #sudo cp $SIGEDGE_SOURCE/LimeSuite/Desktop/lime-suite-32.png $DESKTOP_ICONS/lime-suite.png
        # Add Desktop
        #sudo cp $SIGEDGE_SOURCE/LimeSuite/Desktop/lime-suite.desktop $DESKTOP_FILES
        # Change Category
        #sudo sed -i "s/Categories.*/Categories=$SIGEDGE_MENU_CATEGORY;/" $DESKTOP_FILES/lime-suite.desktop
        # Add to Menu
        #xdg-desktop-menu install --novendor --noupdate $DESKTOP_DIRECTORY/SIGpi.directory $DESKTOP_FILES/lime-suite.desktop

        cat $SIGEDGE_DEVLIST|grep "limesuite" >> $SIGEDGE_INSTALLED_DEVICES
        ;;&

    build|package)
        ## PACKAGE
        cd $SIGEDGE_SOURCE
        git clone https://github.com/myriadrf/LimeSuite.git
        cd LimeSuite
        git checkout stable
        mkdir build-dir && cd build-dir
        cmake .. -Wno-dev
        make -j4
        ;;&

    build )
        sudo make install
        cat $SIGEDGE_DEVLIST|grep "limesuite" >> $SIGEDGE_INSTALLED_DEVICES
        ;;&

    package)
        sudo checkinstall --install=no
        sudo mv *.deb $SIGEDGE_DEBS
        ;;&

    install|build|package|remove|purge )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##   $1 : LimeSDR Devices completed"
        echo -e "${SIGEDGE_BANNER_RESET}"
        ;;

    * )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##  ERROR: Unkown action or package"
        echo -e "${SIGEDGE_BANNER_RESET}"
        ;;
esac
