#!/bin/bash

###
### SIGpi
###
### pkg_libfobos
###
###
### 20260120-2300
###
### RigExpert Fobos Device
###


if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
    echo -e "${SIGEDGE_BANNER_COLOR}"
    echo -e "${SIGEDGE_BANNER_COLOR} ##  ERROR: Unknown action or package"
    echo -e "${SIGEDGE_BANNER_RESET}"
    exit 1
fi

case "$1" in
    remove|purge|install|build|package )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##  $1 : RigExpert Fobos"
        echo -e "${SIGEDGE_BANNER_RESET}"
        ;;&

   remove )
        sudo dpkg -r libfobos
        sudo dpkg -r soapyfobos
        sed -i /libfobos/d $SIGEDGE_INSTALLED_DEVICES
        sed -i /soapyfobos/d $SIGEDGE_INSTALLED_DEVICES
        ;;&

    purge )
        sudo dpkg -P libfobos
        sudo dpkg -P soapyfobos
        sed -i /libfobos/d $SIGEDGE_INSTALLED_DEVICES
        sed -i /soapyfobos/d $SIGEDGE_INSTALLED_DEVICES
        rm -rf $SIGEDGE_SOURCE/libfobos
        rm -rf $SIGEDGE_SOURCE/SoapyFobosSDR
        ;;&

    install )
        ## PACKAGE
        cd $SIGEDGE_PACKAGES
        if [[ "$SIGEDGE_HWARCH" == "x86_64" ]]; then
	        cd $SIGEDGE_DEBS
	        sudo dpkg -i libfobos_current_amd64.deb
            sudo dpkg -i soapyfobos_current_amd64.deb
        fi

        if [[ "$SIGEDGE_HWARCH" == "aarch64" ]]; then
	        cd $SIGEDGE_DEBS
            sudo dpkg -i libfobos_current_arm64.deb
            sudo dpkg -i soapyfobos_current_arm64.deb
        fi
        cat $SIGEDGE_DEVLIST|grep "libfobos" >> $SIGEDGE_INSTALLED_DEVICES
        cat $SIGEDGE_DEVLIST|grep "soapyfobos" >> $SIGEDGE_INSTALLED_DEVICES
        ;;&

    build )
        ## Fobos driver
        cd $SIGEDGE_SOURCE
        git clone https://github.com/rigexpert/libfobos
        cd libfobos
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4
        sudo make install
        sudo udevadm control --reload-rules
        sudo udevadm trigger
        cat $SIGEDGE_DEVLIST|grep "libfobos" >> $SIGEDGE_INSTALLED_DEVICES

        ## SoapyFobosSDR Driver
        cd $SIGEDGE_SOURCE
        git clone https://github.com/rigexpert/SoapyFobosSDR
        cd SoapyFobosSDR
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4
        sudo make install
        sudo ldconfig
        cat $SIGEDGE_DEVLIST|grep "soapyfobos" >> $SIGEDGE_INSTALLED_DEVICES
        ;;&

    package)
        ## Fobos driver
        cd $SIGEDGE_SOURCE
        git clone https://github.com/rigexpert/libfobos
        cd libfobos
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4
        sudo checkinstall --install=no
        sudo mv *.deb $SIGEDGE_DEBS

        ## SoapyFobosSDR Driver
        cd $SIGEDGE_SOURCE
        git clone https://github.com/rigexpert/SoapyFobosSDR
        cd SoapyFobosSDR
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4
        sudo checkinstall --install=no
        sudo mv *.deb $SIGEDGE_DEBS
        ;;&

    install|build|package|remove|purge )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##  $1 : RigExpert Fobos completed"
        echo -e "${SIGEDGE_BANNER_RESET}"
        ;;
esac