#!/bin/bash

###
### SIGPI
###
### pkg_ubertooth
###
###
### 20260114-2300
###
### Ubertooth One is an open source 2.4 GHz wireless
### development platform suitable for Bluetooth experimentation
###

if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
    echo -e "${SIGEDGE_BANNER_COLOR}"
    echo -e "${SIGEDGE_BANNER_COLOR} ##  ERROR: Unknown case "$1" in wn action or package"
    echo -e "${SIGEDGE_BANNER_RESET}"
    exit 1
fi

case "$1" in
    remove|purge|install|build|package )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##  $1 : ubertooth"
        echo -e "${SIGEDGE_BANNER_RESET}"
        ;;&

    remove )
        cd $SIGEDGE_SOURCE/libbtbb/build
        sudo make uninstall
        cd $SIGEDGE_SOURCE
        rm -rf $SIGEDGE_SOURCE/libbtbb
        sed -i /libbtbb/d $SIGEDGE_INSTALLED

        cd $SIGEDGE_SOURCE/ubertooth/host/build
        sudo make uninstall
        cd $SIGEDGE_SOURCE
        rm -rf $SIGEDGE_SOURCE/ubertooth
        sed -i /ubertooth/d $SIGEDGE_INSTALLED_DEVICES
        ;;&

    purge )
        cd $SIGEDGE_SOURCE/libbtbb/build
        sudo make uninstall
        cd $SIGEDGE_SOURCE
        rm -rf $SIGEDGE_SOURCE/libbtbb
        sed -i /libbtbb/d $SIGEDGE_INSTALLED

        cd $SIGEDGE_SOURCE/ubertooth/host/build
        sudo make uninstall
        cd $SIGEDGE_SOURCE
        rm -rf $SIGEDGE_SOURCE/ubertooth
        sed -i /ubertooth/d $SIGEDGE_INSTALLED_DEVICES

        ### Remove Menu icon
        sudo rm $SIGEDGE_DESKTOP_ICONS/ubertooth-tools.png
        ### Remove Desktop links
        sudo rm $SIGEDGE_DESKTOP_FILES/ubertooth-tools.desktop
        ;;&

    install|build )
        ## DEPENDENCIES
        sudo apt-get install -y libusb-1.0-0-dev
        sudo apt-get install -y libbluetooth-dev
        sudo apt-get install -y python3-qtpy
        #sudo apt-get install -y python3-distutils
        sudo apt-get install -y python3-setuptools

        ### LibBTBB Library
        cd $SIGEDGE_SOURCE
        git clone https://github.com/greatscottgadgets/libbtbb.git
        cd libbtbb
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4
        sudo make install
        sudo ldconfig
        cat $SIGEDGE_PKGLIST|grep "libbtbb" >> $SIGEDGE_INSTALLED

        ### Ubertooth
        cd $SIGEDGE_SOURCE
        git clone https://github.com/greatscottgadgets/ubertooth.git
        cd ubertooth/host
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4
        sudo make install
        cat $SIGEDGE_DEVLIST|grep "libbtbb" >> $SIGEDGE_INSTALLED_DEVICES
        ;;&

    package )
        ## DEPENDENCIES
        sudo apt-get install -y libusb-1.0-0-dev
        sudo apt-get install -y libbluetooth-dev
        sudo apt-get install -y python3-qtpy
        #sudo apt-get install -y python3-distutils
        sudo apt-get install -y python3-setuptools

        ### LibBTBB Library
        cd $SIGEDGE_SOURCE
        git clone https://github.com/greatscottgadgets/libbtbb.git
        cd libbtbb
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4
        sudo checkinstall --install=no
        sudo mv *.deb $SIGEDGE_DEBS

        ### Ubertooth
        cd $SIGEDGE_SOURCE
        git clone https://github.com/greatscottgadgets/ubertooth.git
        cd ubertooth/host
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4
        sudo checkinstall --install=no
        sudo mv *.deb $SIGEDGE_DEBS
	    ;;&

    remove|purge|install|build|package )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##  $1 : ubertooth - Completed"
        echo -e "${SIGEDGE_BANNER_RESET}"
        ;;
esac