#!/bin/bash

###
### SIGPI
###
### pkg_sdrplay
###
### 20260124-2300
###
###
###

if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
    echo -e "${SIGEDGE_BANNER_COLOR}"
    echo -e "${SIGEDGE_BANNER_COLOR} ##  ERROR: Unknown action or package"
    echo -e "${SIGEDGE_BANNER_RESET}"
    exit 1
fi

case "$1" in
    remove|purge|install|build|package )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##  $1 : SDRplay"
        echo -e "${SIGEDGE_BANNER_RESET}"
        ;;&

    remove|purge )
	    cd $SIGEDGE_SOURCE/SDRplay/build/host
        sudo make uninstall
        sudo ldconfig
        cd $SIGEDGE_SOURCE
        rm -rf $SIGEDGE_SOURCE/SDRplay
        rm -rf $HOME/.config/SDRplay
        sudo rm -rf $SIGEDGE_DESKTOP/SDRplay.desktop
        sudo rm -rf $DESKTOP_FILES/SDRplay.desktop
        sed -i /sdrplay/d $SIGEDGE_INSTALLED_DEVICES
        ;;&

    install )
        cd $SIGEDGE_SOURCE
        unzip $SIGEDGE_DEBS/SDRplay_RSP_API.zip
        cd SDRplay_RSP_API
        sudo ./install_lib.sh
        sudo cp $SIGEDGE_SCRIPTS/run_SDRplay.sh /usr/local/bin/run_SDRplay.sh
        sudo chmod 755 /usr/local/bin/run_SDRplay.sh
        cat $SIGEDGE_DEVLIST|grep "sdrplay" >> $SIGEDGE_INSTALLED_DEVICES
        ;;&

    remove|purge|install|build|package )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##  $1 : SDRplay - Completed"
        echo -e "${SIGEDGE_BANNER_RESET}"
        ;;
esac