#!/bin/bash

###
### SIGPI
###
### pkg_rtlsdr
###
###
### 2026087-2300
###
### RTLSDR v4
###

if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
    echo -e "${SIGEDGE_BANNER_COLOR}"
    echo -e "${SIGEDGE_BANNER_COLOR} ##  ERROR: Unknown action or package"
    echo -e "${SIGEDGE_BANNER_RESET}"
    exit 1
fi

case "$1" in
    remove|purge|install|build|package )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##  $1 : rtlsdr: Start"
        echo -e "${SIGEDGE_BANNER_RESET}"
        ;;&

    remove|purge )
        cd $SIGEDGE_SOURCE/rtl-sdr-blog/build
        sudo make uninstall
        sudo ldconfig
        cd $SIGEDGE_SOURCE
	    rm -rf $SIGEDGE_SOURCE/rtl-sdr-blog
        sed -i /rtlsdr/d $SIGEDGE_INSTALLED_DEVICES
        ;;&

    install|build|package )
        ## DEPENDENCIES
        sudo apt purge -y ^librtlsdr
        sudo rm -rvf /usr/lib/librtlsdr* /usr/include/rtl-sdr* /usr/local/lib/librtlsdr* /usr/local/include/rtl-sdr* /usr/local/include/rtl_* /usr/local/bin/rtl_*
        sudo apt-get install -y libusb-1.0-0-dev
        ;;&

    install|build )
        ## PACKAGE
        cd $SIGEDGE_SOURCE
        git clone https://github.com/rtlsdrblog/rtl-sdr-blog
        cd rtl-sdr-blog
        mkdir build && cd build
        cmake ../ -DINSTALL_UDEV_RULES=ON -DDETACH_KERNEL_DRIVER=ON -DENABLE_ZEROCOPY=ON
        make -j4
        sudo make install
        sudo ldconfig
        echo 'blacklist dvb_usb_rtl28xxu' | sudo tee --append /etc/modprobe.d/blacklist-rtl.conf
        grep "^rtlsdr," "$SIGEDGE_DEVLIST" >> $SIGEDGE_INSTALLED_DEVICES

        cd $SIGEDGE_SOURCE
        git clone https://github.com/pothosware/SoapyRTLSDR.git
        cd SoapyRTLSDR
        mkdir build && cd build
        cmake .. -Wno-dev -DCMAKE_BUILD_TYPE=Release
        make -j4
        sudo make install
        sudo ldconfig
        ;;&

     package )
        ## PACKAGE
        cd $SIGEDGE_SOURCE
        git clone https://github.com/rtlsdrblog/rtl-sdr-blog
        cd rtl-sdr-blog
        mkdir build && cd build
        cmake ../ -DINSTALL_UDEV_RULES=ON
        make -j4
        sudo checkinstall --install=no
        sudo mv *.deb $SIGEDGE_DEBS

        cd $SIGEDGE_SOURCE
        git clone https://github.com/pothosware/SoapyRTLSDR.git
        cd SoapyRTLSDR
        mkdir build && cd build
        cmake .. -Wno-dev -DCMAKE_BUILD_TYPE=Release
        make -j4
        sudo checkinstall --install=no
        sudo mv *.deb $SIGEDGE_DEBS
        ;;&

    remove|purge|install|build|package )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##  $1 : rtlsdr: Completed"
        echo -e "${SIGEDGE_BANNER_RESET}"
        ;;
esac
