#!/bin/bash

###
### SIGPI
###
### pkg_gpredict
###
###
### 20260113-2300
###

if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
    echo -e "${SIGEDGE_BANNER_COLOR}"
    echo -e "${SIGEDGE_BANNER_COLOR} ##  ERROR: Unknown action or package"
    echo -e "${SIGEDGE_BANNER_RESET}"
    exit 1
fi

case "$1" in
    remove|purge|install|build|package )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##  $1 : Gpredict"
        echo -e "${SIGEDGE_BANNER_RESET}"
        ;;&

    remove )
        sudo apt-get remove gpredict
        sed -i /gpredict/d $SIGEDGE_INSTALLED
        ;;&

    purge )
        sudo apt-get remove --purge gpredict
        sed -i /gpredict/d $SIGEDGE_INSTALLED
        rm -rf $HOME/.config/Gpredict
        sudo rm -rf $SIGEDGE_DESKTOP/gpredict.desktop
        sudo rm -rf $DESKTOP_FILES/gpredict.desktop
        ;;&

    install|build|package )
        ## DEPENDENCIES
        sudo apt-get install -y libtool intltool autoconf automake
        sudo apt-get install -y libcurl4-openssl-dev
        sudo apt-get install -y pkg-config libglib2.0-dev libgtk-3-dev
        sudo apt-get install -y libgoocanvas-2.0-dev
        ;;&

    install )
        ## PACKAGE
        cd $SIGEDGE_PACKAGES
        if [[ "$SIGEDGE_HWARCH" == "x86_64" ]]; then
	        cd $SIGEDGE_DEBS
	        sudo dpkg -i gpredict_current_amd64.deb
        fi

        if [[ "$SIGEDGE_HWARCH" == "aarch64" ]]; then
	        cd $SIGEDGE_DEBS
	        sudo dpkg -i gpredict_current_arm64.deb
        fi
        cat $SIGEDGE_PKGLIST|grep "gpredict" >> $SIGEDGE_INSTALLED

        ## DESKTOP
	    # Add Icon
        # Add Desktop
        # Change Category
	    #sudo sed -i "s/Categories.*/Categories=$SIGEDGE_MENU_CATEGORY;/" $DESKTOP_FILES/gpredict.desktop
        # Add to Menu
        #xdg-desktop-menu install --novendor --noupdate $DESKTOP_DIRECTORY/SIGpi.directory $DESKTOP_FILES/gpredict.desktop
        ;;&

    build )
        cd $SIGEDGE_SOURCE
        git clone https://github.com/csete/gpredict.git
        cd gpredict
        ./autogen.sh
        make -j4
        sudo make install
        cat $SIGEDGE_PKGLIST|grep "gpredict" >> $SIGEDGE_INSTALLED
	    ;;&

    package )
        cd $SIGEDGE_SOURCE
        git clone https://github.com/csete/gpredict.git
        cd gpredict
        ./autogen.sh
        make -j4
        sudo checkinstall --install=no
        sudo mv *.deb $SIGEDGE_DEBS
        ;;&

    remove|purge|install|build|package )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##  $1 : Gpredict - Completed"
        echo -e "${SIGEDGE_BANNER_RESET}"
        ;;
esac
