#!/usr/bin/env sh

###
### SIGedge
###
### SIGedge_exec-in-shell
###

###
###  REVISION: 20260827-2300
###

echo "$ $@"
eval $@

USER=${USER:-$(whoami)}
SHELL=${SHELL:-$(getent passwd $USER | cut -d: -f7)}
${SHELL:-bash} -i