#!/bin/bash

###
### SIGPI
###
### pkg_urh
###
###
### 20260828-1902
###
### Universal Radio hacker install
###
###

if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
    echo -e "${SIGEDGE_BANNER_COLOR}"
    echo -e "${SIGEDGE_BANNER_COLOR} ##  ERROR: Unknown action or package"
    echo -e "${SIGEDGE_BANNER_RESET}"
    exit 1
fi

case "$1" in
    remove|purge|install|build|package )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##  $1 : Universal Radio Hacker (URH)"
        echo -e "${SIGEDGE_BANNER_RESET}"
        ;;&

    remove )
        sudo python3 -m pip uninstall urh
        sed -i /urh/d $SIGEDGE_INSTALLED
        sudo rm -f $DESKTOP_FILES/urh.desktop
        ;;&

    purge )
        sudo python3 -m pip uninstall urh
        sed -i /urh/d $SIGEDGE_INSTALLED
        sudo rm -f $DESKTOP_FILES/urh.desktop
        ;;&

    install|build )
        ## DEPENDENCIES
        sudo apt-get install -y build-essential cython3 python3 python3-dev
        sudo apt-get install -y python3-numpy python3-pip python3-psutil
        sudo apt-get install -y python3-pyqt6 python3-setuptools

        ## PACKAGE
        cd $SIGEDGE_PACKAGES
        if [[ "$SIGEDGE_HWARCH" == "x86_64" ]]; then
	        cd $SIGEDGE_SOURCE
            git clone https://github.com/jopohl/urh.git
            cd urh
            sudo python3 setup.py install

            ## DESKTOP
	        # Add Icon
            #sudo cp $SIGEDGE_ICONS/myicon.png $DESKTOP_ICONS
            # Add Desktop
            sudo cp $SIGEDGE_DESKTOP/urh.desktop $DESKTOP_FILES
            # Change Category
            # Add to Menu

            cat $SIGEDGE_PKGLIST|grep "urh" >> $SIGEDGE_INSTALLED
        else
            echo -e "${SIGEDGE_BANNER_COLOR}"
            echo -e "${SIGEDGE_BANNER_COLOR} ##   URH not stable for Raspberry Pi OS"
            echo -e "${SIGEDGE_BANNER_RESET}"
        fi
        ;;&

    package )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##  $1 : option not available"
        echo -e "${SIGEDGE_BANNER_RESET}"
        ;;&

    remove|purge|install )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##  $1 : Universal Radio Hacker (URH) - Completed"
        echo -e "${SIGEDGE_BANNER_RESET}"
        ;;
esac