#!/bin/bash

###
### SIGpi
###
### pkg_rnnoise
###
###
### 20260124-1200
###
### Recurrent neural network for audio noise reduction
###

if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
    echo -e "${SIGEDGE_BANNER_COLOR}"
    echo -e "${SIGEDGE_BANNER_COLOR} ##  ERROR: Unknown action or package"
    echo -e "${SIGEDGE_BANNER_RESET}"
    exit 1
fi

case "$1" in
    remove|purge|install|build|package )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##  $1 : RNNoise"
        echo -e "${SIGEDGE_BANNER_RESET}"
        ;;&

    remove )
        sudo dpkg -r rnnoise
        sed -i /rnnoise/d $SIGEDGE_INSTALLED
        ;;&

    purge )
        sudo dpkg -P rnnoise
        sed -i /rnnoise/d $SIGEDGE_INSTALLED
        ;;&

    install )
        ## PACKAGE
        cd $SIGEDGE_PACKAGES
        if [[ "$SIGEDGE_HWARCH" == "x86_64" ]]; then
	        cd $SIGEDGE_DEBS
	        sudo dpkg -i rnnoise_current_amd64.deb
        fi

        if [[ "$SIGEDGE_HWARCH" == "aarch64" ]]; then
	        cd $SIGEDGE_DEBS
	        sudo dpkg -i rnnoise_current_arm64.deb
        fi
        cat $SIGEDGE_PKGLIST|grep "rnnoise," >> $SIGEDGE_INSTALLED
        ;;&

    build )
        ## PACKAGE
        cd $SIGEDGE_SOURCE
        git clone https://github.com/f4exb/rnnoise
        cd rnnoise
        mkdir build; cd build

        if [[ "$SIGEDGE_HWARCH" == "x86_64" ]]; then
            cmake -DRNN_ENABLE_X86_RTCD=ON ..
        fi

        if [[ "$SIGEDGE_HWARCH" == "aarch64" ]]; then
            cmake ..
        fi

        make -j4
        sudo make install
        sudo ldconfig
        cat $SIGEDGE_PKGLIST|grep "rnnoise" >> $SIGEDGE_INSTALLED
        ;;&

    package )
        ## PACKAGE
        cd $SIGEDGE_SOURCE
        git clone https://github.com/f4exb/rnnoise
        cd rnnoise
        mkdir build && cd build

        if [[ "$SIGEDGE_HWARCH" == "x86_64" ]]; then
            cmake -DRNN_ENABLE_X86_RTCD=ON ..
        fi

        if [[ "$SIGEDGE_HWARCH" == "aarch64" ]]; then
            cmake ..
        fi

        make -j4
        sudo checkinstall --install=no
        sudo mv *.deb $SIGEDGE_DEBS
        ;;&

    remove|purge|install|build|package|config )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##  $1 : RNNoise - Completed"
        echo -e "${SIGEDGE_BANNER_RESET}"
        ;;
esac