#!/bin/bash

###
### SIGPI
###
### pkg_pavucontrol
###
###
### 20230113-2300
###

if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
    echo -e "${SIGEDGE_BANNER_COLOR}"
    echo -e "${SIGEDGE_BANNER_COLOR} ##  ERROR: Unknown action or package"
    echo -e "${SIGEDGE_BANNER_RESET}"
    exit 1
fi

case "$1" in
    remove|purge|install|build|package )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##  $1 : PAVUcontrol"
        echo -e "${SIGEDGE_BANNER_RESET}"
        ;;&

    remove )
        sudo apt-get remove pavucontrol
        sudo apt-get remove paprefs
        sed -i /pavu/d $SIGEDGE_INSTALLED
        ;;&

    purge )
        sudo apt-get remove --purge pavucontrol
        sudo apt-get remove --purge paprefs
        sed -i /pavu/d $SIGEDGE_INSTALLED
        ;;&

    install )
        ## DEPENDENCIES

        ## PACKAGE
        cd $SIGEDGE_SOURCE
        sudo apt-get install -y pavucontrol
        echo " " >> /etc/pulse/default.pa
        echo "## SIGpi adding Virtual Audio Sink " >> /etc/pulse/default.pa
        echo "load-module module-null-sink sink_name=Virtual_Sink sink_properties=device.description=Virtual_Sink" >> /etc/pulse/default.pa
	    sudo apt-get install -y paprefs
        cat $SIGEDGE_PKGLIST|grep "pavucontrol" >> $SIGEDGE_INSTALLED

        ## DESKTOP
	    # Add Icon
        # Add Desktop
        # Change Category
        # Add to menu
        ;;&

    build )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##   Build option not available"
        echo -e "${SIGEDGE_BANNER_RESET}"
	    ;;

    package )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##   Package option not available"
        echo -e "${SIGEDGE_BANNER_RESET}"
	    ;;

    remove|purge|install )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##  $1 : PAVUcontrol - Completed"
        echo -e "${SIGEDGE_BANNER_RESET}"
        ;;
esac
