#!/bin/bash

###
### SIGPI
###
### pkg_srsran-4g
###
###
### 20260113-2300
###

if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
    echo -e "${SIGEDGE_BANNER_COLOR}"
    echo -e "${SIGEDGE_BANNER_COLOR} ##  ERROR: Unknown action or package"
    echo -e "${SIGEDGE_BANNER_RESET}"
    exit 1
fi

case "$1" in
    remove|purge|install|build|package )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##  $1 : srsRAN-4g"
        echo -e "${SIGEDGE_BANNER_RESET}"
        ;;&

    remove )
        sudo dpkg -r srsran-4g
        sed -i /srsran-4g/d $SIGEDGE_INSTALLED
        ;;&

    purge )
        sudo dpkg -P srsran-4g
        sed -i /srsran-4g/d $SIGEDGE_INSTALLED
        ;;&

    install )
        ## DEPENDENCIES
        sudo apt-get install -y libmbedtls-dev libboost-program-options-dev
        sudo apt-get install -y libconfig++-dev libsctp-dev

        ## PACKAGE
        cd $SIGEDGE_DEBS
        if [[ "$SIGEDGE_HWARCH" == "x86_64" ]]; then
	        sudo dpkg -i srsran-4g_current_amd64.deb
            cat $SIGEDGE_PKGLIST|grep "srsran-4g" >> $SIGEDGE_INSTALLED
        fi

        if [[ "$SIGEDGE_HWARCH" == "aarch64" ]]; then
	        sudo dpkg -i srsran-4g_current_arm64.deb
            cat $SIGEDGE_PKGLIST|grep "srsran-4g" >> $SIGEDGE_INSTALLED
        fi
	    ;;&

    build )
        ## DEPENDENCIES
        sudo apt-get install -y libmbedtls-dev libboost-program-options-dev
        sudo apt-get install -y libconfig++-dev libsctp-dev
        cd $SIGEDGE_SOURCE
        git clone https://github.com/srsRAN/srsRAN_4G.git
        cd srsRAN_4G
        mkdir build ; cd build
        cmake ../
        make -j4
        sudo make install
        cat $SIGEDGE_PKGLIST|grep "srsran-4g" >> $SIGEDGE_INSTALLED
        ;;&

    package )
        ## DEPENDENCIES
        sudo apt-get install -y libmbedtls-dev libboost-program-options-dev
        sudo apt-get install -y libconfig++-dev libsctp-dev
        cd $SIGEDGE_SOURCE
        git clone https://github.com/srsRAN/srsRAN_4G.git
        cd srsRAN_4G
        mkdir build ; cd build
        cmake ../
        make -j4
        sudo checkinstall --install=no
        sudo mv *.deb $SIGEDGE_DEBS
	    ;;&

    remove|purge|install|build|package )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##  $1 : srsRAN-4g - Completed"
        echo -e "${SIGEDGE_BANNER_RESET}"
        ;;
esac
