#!/bin/bash

###
### SIGPI
###
### pkg_gqrx
###
###
### 20260113-2300
###

if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
    echo -e "${SIGEDGE_BANNER_COLOR}"
    echo -e "${SIGEDGE_BANNER_COLOR} ##  ERROR: Unknown action or package"
    echo -e "${SIGEDGE_BANNER_RESET}"
    exit 1
fi

case "$1" in
    remove|purge|install|build|package )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##  $1 : Gqrx"
        echo -e "${SIGEDGE_BANNER_RESET}"
        ;;&

    remove )
        sudo apt-get remove gqrx-sdr
        sed -i /gqrx/d $SIGEDGE_INSTALLED
        ;;&

    purge )
        sudo apt-get remove --purge gqrx-sdr
        sed -i /gqrx/d $SIGEDGE_INSTALLED
        ;;&

    install )
        ## DEPENDENCIES

        ## PACKAGE
        cd $SIGEDGE_SOURCE
        sudo apt-get install -y gqrx-sdr
        cat $SIGEDGE_PKGLIST|grep "gqrx" >> $SIGEDGE_INSTALLED

        ## DESKTOP
	    # Add Icon
        # Add Desktop
        # Change Category
	    #sudo sed -i "s/Categories.*/Categories=$SIGEDGE_MENU_CATEGORY;/" $DESKTOP_FILES/gqrx.desktop
        # Add to Menu
        #xdg-desktop-menu install --novendor --noupdate $DESKTOP_DIRECTORY/SIGpi.directory $DESKTOP_FILES/gqrx.desktop
        ;;&

    build )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##   Build option not available"
        echo -e "${SIGEDGE_BANNER_RESET}"
	    ;;&

    package )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##   Package option not available"
        echo -e "${SIGEDGE_BANNER_RESET}"
	    ;;&

    remove|purge|install )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##  $1 : Gqrx - Completed"
        echo -e "${SIGEDGE_BANNER_RESET}"
        ;;
esac
