#!/bin/bash

###
### SIGpi
###
### pkg_liquid-dsp
###
###
### 20260113-2300
###
### liquid-dsp is a free and open-source digital signal processing (DSP) library designed specifically for software-defined radios on embedded platforms.
### The aim is to provide a lightweight DSP library that does not rely on a myriad of external dependencies or proprietary and otherwise cumbersome frameworks.
### All signal processing elements are designed to be flexible, scalable, and dynamic, including filters, filter design, oscillators, modems,
### synchronizers, complex mathematical operations, and much more.
###

if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
    echo -e "${SIGEDGE_BANNER_COLOR}"
    echo -e "${SIGEDGE_BANNER_COLOR} ##  ERROR: Unknown action or package"
    echo -e "${SIGEDGE_BANNER_RESET}"
    exit 1
fi

case "$1" in
    remove|purge|install|build|package )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##  $1 : Liquid-DSP"
        echo -e "${SIGEDGE_BANNER_RESET}"
        ;;&

    remove )
        cd $SIGEDGE_PACKAGES
        if [[ "$SIGEDGE_HWARCH" == "x86_64" ]]; then
	        cd $SIGEDGE_DEBS
            sudo dpkg -r liquid-dsp
            sed -i /liquid-dsp/d $SIGEDGE_INSTALLED
        fi

        if [[ "$SIGEDGE_HWARCH" == "aarch64" ]]; then
	        cd $SIGEDGE_DEBS
            sudo dpkg -r liquid-dsp
            sed -i /liquid-dsp/d $SIGEDGE_INSTALLED
        fi
        ;;&

    purge )
        cd $SIGEDGE_PACKAGES
        if [[ "$SIGEDGE_HWARCH" == "x86_64" ]]; then
	        cd $SIGEDGE_DEBS
            sudo dpkg -P liquid-dsp
            sed -i /liquid-dsp/d $SIGEDGE_INSTALLED
        fi

        if [[ "$SIGEDGE_HWARCH" == "aarch64" ]]; then
	        cd $SIGEDGE_DEBS
            sudo dpkg -P liquid-dsp
            sed -i /liquid-dsp/d $SIGEDGE_INSTALLED
        fi
        ;;&

    install)
        ## PACKAGE
        cd $SIGEDGE_PACKAGES
        if [[ "$SIGEDGE_HWARCH" == "x86_64" ]]; then
	        cd $SIGEDGE_DEBS
	        sudo dpkg -i liquid-dsp_current_amd64.deb
        fi

        if [[ "$SIGEDGE_HWARCH" == "aarch64" ]]; then
	        cd $SIGEDGE_DEBS
	        sudo dpkg -i liquid-dsp_current_arm64.deb
        fi
        cat $SIGEDGE_PKGLIST|grep "liquid-dsp" >> $SIGEDGE_INSTALLED

	    ## DESKTOP
	    # Add Icon
        # Add Desktop
        # Change Category
	    # Add to Menu
        ;;&

    build )
        ## DEPENDENCIES

        ## PACKAGE
        cd $SIGEDGE_SOURCE
        git clone https://github.com/jgaeddert/liquid-dsp.git
        cd liquid-dsp
        ./bootstrap.sh
        ./configure --enable-fftoverride
        make -j4
        sudo make install
        sudo ldconfig
        cat $SIGEDGE_PKGLIST|grep "liquid-dsp" >> $SIGEDGE_INSTALLED

        ## DESKTOP
	    # Add Icon
        # Add Desktop
        # Change Category
	    # Add to Menu
        ;;&

    package )
        ## DEPENDENCIES

        ## PACKAGE
        cd $SIGEDGE_SOURCE
        git clone https://github.com/jgaeddert/liquid-dsp.git
        cd liquid-dsp
        ./bootstrap.sh
        ./configure --enable-fftoverride
        make -j4
        sudo checkinstall --install=no
        sudo mv *.deb $SIGEDGE_DEBS

        ## DESKTOP
	    # Add Icon
        # Add Desktop
        # Change Category
	    # Add to Menu
        ;;&

    remove|purge|install|build|package )
        echo -e "${SIGEDGE_BANNER_COLOR}"
        echo -e "${SIGEDGE_BANNER_COLOR} ##  $1 : Liquid-DSP - Completed"
        echo -e "${SIGEDGE_BANNER_RESET}"
        ;;
esac
