#!/bin/bash

###
### SIGedge
###
### setup_start
###

###
###  REVISION: 20260827-2300
###

###
###  Usage:    setup_start
###
###            Fresh install of SIGedge on a fresh OS install
###
###
###

###
### Environment tests
###

# Hardware and operating system must both be supported.
case "$SIGEDGE_HWARCH" in
    x86_64|aarch64|ARMv8) ;;
    *) SIGEDGE_CERTIFIED="false" ;;
esac

case "$SIGEDGE_OSNAME" in
    *"Ubuntu 24.04"*|*"Debian GNU/Linux 13"*)
        if [[ "$SIGEDGE_HWARCH" =~ ^(x86_64|aarch64|ARMv8)$ ]]; then
            SIGEDGE_CERTIFIED="true"
        fi
        ;;
    *) SIGEDGE_CERTIFIED="false" ;;
esac
if [ "$SIGEDGE_CERTIFIED" = "false" ]; then
    echo "ERROR:"
    echo "ERROR:  Incorrect Hardware or Operating System"
    echo "ERROR:"
    echo "ERROR:  Hardware must be x86_64 or ARMv8 - Aborting"
    echo "ERROR:  Operating system must be Ubuntu 24.04 or Debian Trixie - Aborting"
    echo "ERROR:"
    exit 1;
fi


###
### FUNCTIONS
###

calc_wt_size() {
  # NOTE: it's tempting to redirect stderr to /dev/null, so supress error
  # output from tput. However in this case, tput detects neither stdout or
  # stderr is a tty and so only gives default 80, 24 values
  WT_HEIGHT=26
  WT_WIDTH=$(tput cols)

  if [ -z "$WT_WIDTH" ] || [ "$WT_WIDTH" -lt 60 ]; then
    WT_WIDTH=60
  fi
  if [ "$WT_WIDTH" -gt 178 ]; then
    WT_WIDTH=80
  fi
  WT_MENU_HEIGHT=$(($WT_HEIGHT-7))
}

select_startscreen(){
    TERM=ansi whiptail --title "SIGedge Setup" --clear --msgbox \
        "Configure this SIGedge node, select SDR hardware, and choose optional direct-access services." 12 80
}

select_devices() {
    FUN=$(whiptail --title "Devices Setup" --clear --checklist --separate-output \
        "Choose SDR devices " 20 80 12 \
        "rtlsdr" "RTLSDR v3/4" ON\
        "hackrf" "HackRF v1" ON\
        "rx888" "RX-888 MkII " OFF\
        "bladerf" "bladeRF " OFF \
        "ettus" "Ettus Research USRP UHD " OFF \
        "fobos" "RigExpert Fobos " OFF\
        "kerberos" "Kerberos SDR " OFF\
        "limesuite" "LimeSDR " OFF \
        "plutosdr" "PlutoSDR " OFF \
        "sdrplay" "SDRPlay " OFF \
        "ubertooth" "Ubertooth One" OFF \
        3>&1 1>&2 2>&3)
    RET=$?
    if [ $RET -eq 1 ]; then
        FUN=""
    fi

    IFS=' '     # space is set as delimiter
    read -ra ADDR <<< "$FUN"   # str is read into an array as tokens separated by IFS
    for i in "${ADDR[@]}"; do   # access each element of array
        echo "$i" >> "$SIGEDGE_INSTALLED_DEVICES"
    done
}

select_services() {
    FUN=$(whiptail --title "Services Installation" --clear --checklist --separate-output \
        "Choose which services to install" 20 120 12 \
        "ka9q-radio" "KA9Q-Radio " OFF \
        "openwebrx" "OpenWebRX " OFF \
        "rtltcpsrv" "RTL-TCP Server " OFF \
        "sdrangelsrv" "SDRangel Server " OFF \
        "soapysdrsrv" "SoapySDR Server " OFF \
		3>&1 1>&2 2>&3)
    RET=$?
    if [ $RET -eq 1 ]; then
        FUN=""
    fi

    IFS=' '     # space is set as delimiter
    read -ra ADDR <<< "$FUN"   # str is read into an array as tokens separated by IFS
    for i in "${ADDR[@]}"; do   # access each element of array
        echo "$i" >> "$SIGEDGE_INSTALLED_SERVICES"
    done
}

system_current() {
    echo -e "${SIGEDGE_BANNER_COLOR}"
    echo -e "${SIGEDGE_BANNER_COLOR} ##"
    echo -e "${SIGEDGE_BANNER_COLOR} ##  System Update & Upgrade"
    echo -e "${SIGEDGE_BANNER_COLOR} ##"
    echo -e "${SIGEDGE_BANNER_RESET}"

    sudo apt-get -y update
    sudo apt-get -y upgrade
}


###
###  MAIN
###

# Setup directories
mkdir -p "$SIGEDGE_ETC"
touch "$SIGEDGE_INSTALLED"
touch "$SIGEDGE_INSTALLED_DEVICES"
touch "$SIGEDGE_INSTALLED_SERVICES"
mkdir -p "$SIGEDGE_SOURCE"
cd "$SIGEDGE_SOURCE" || return 1

calc_wt_size
select_startscreen
select_devices
select_services
TERM=ansi whiptail --title "SIGedge Setup" --clear --msgbox "Ready to continue" 12 120
system_current

cd "$SIGEDGE_SOURCE" || return 1

source "$SIGEDGE_SCRIPTS/setup_core" || return 1
source "$SIGEDGE_SCRIPTS/setup_devices" || return 1
source "$SIGEDGE_SCRIPTS/setup_decoders" || return 1
source "$SIGEDGE_SCRIPTS/setup_services" || return 1

# Expose the repository command without copying it away from its support files.
sudo ln -sfn "$SIGEDGE_HOME/SIGedge" /usr/local/bin/SIGedge

# Install RTL-TCP Server
if [ "$2" = "rtltcpsrv" ]; then
    sudo cp $SIGEDGE_CONFIG/rtltcp.service /etc/systemd/system/sigpi-node.service
    echo "sigpi-node_rtltcp" >> $SIGEDGE_INSTALLED
fi

# Install SDRangel Server
if [ "$2" = "sdrangelsrv" ]; then
    source $SIGEDGE_PACKAGES/pkg_sdrangelsrv install
    sudo cp $SIGEDGE_CONFIG/sdrangelsrv.service /etc/systemd/system/sigpi-node.service
    echo "sigpi-node_sdrangelsrv" >> $SIGEDGE_INSTALLED
fi

# Install SoapySDR Server
if [ "$2" = "soapysdrsrv" ]; then
    sudo cp $SIGEDGE_CONFIG/soapysdrsrv.service /etc/systemd/system/sigpi-node.service
    echo "sigpi-node_soapysdrsrv" >> $SIGEDGE_INSTALLED
fi

# Install OpenWebRX
if [ "$2" = "openwebrx" ]; then
    source $SIGEDGE_PACKAGES/pkg_openwebrx install
    sudo cp $SIGEDGE_CONFIG/scripts/openwebrx.service /etc/systemd/system/openwebrx.service
    echo "sigpi-node_openwebrx" >> $SIGEDGE_INSTALLED
fi

echo -e "${SIGEDGE_BANNER_COLOR}"
echo -e "${SIGEDGE_BANNER_COLOR} ##"
echo -e "${SIGEDGE_BANNER_COLOR} ##  Setup Complete !!"
echo -e "${SIGEDGE_BANNER_COLOR} ##"
echo -e "${SIGEDGE_BANNER_COLOR}"
echo -e "${SIGEDGE_BANNER_COLOR} ##"
echo -e "${SIGEDGE_BANNER_COLOR} ##  System needs to reboot for all changes to occur"
echo -e "${SIGEDGE_BANNER_COLOR} ##  Reboot will begin in 15 seconsds unless CTRL-C hit"
echo -e "${SIGEDGE_BANNER_COLOR} ##"
echo -e "${SIGEDGE_BANNER_RESET}"
sleep 15
sudo sync
sudo reboot
exit 0