#!/bin/bash

###
### SIGpi
###
### setup_core
###
###
### 20260827-2300
###

echo -e "${SIGEDGE_BANNER_COLOR}"
echo -e "${SIGEDGE_BANNER_COLOR} ##"
echo -e "${SIGEDGE_BANNER_COLOR} ##  Setup Core: Starting"
echo -e "${SIGEDGE_BANNER_COLOR} ##"
echo -e "${SIGEDGE_BANNER_RESET}"

# Repos
sudo add-apt-repository universe -y
sudo apt update && sudo apt upgrade -y

# Baseline
sudo apt-get install -y build-essential pkg-config git cmake g++ gcc autoconf automake libtool libgl1-mesa-dev
sudo apt-get install -y libssl-dev libavahi-client-dev libavahi-common-dev libaio-dev net-tools
sudo apt-get install -y libtool libudev1 libusb-1.0-0 libusb-1.0-0-dev libusb-dev
sudo apt-get install -y libsamplerate-dev libcurl4-openssl-dev

# Python Baseline
sudo apt-get install -y python3-pip
sudo apt-get install -y python3-cairocffi
sudo apt-get install -y python3-click
sudo apt-get install -y python3-click-plugins
sudo apt-get install -y python3-gi-cairo
sudo apt-get install -y python3-lxml
sudo apt-get install -y python3-mako
sudo apt-get install -y python3-matplotlib
sudo apt-get install -y python3-numpy
sudo apt-get install -y python3-pyqtgraph
sudo apt-get install -y python3-scipy
sudo apt-get install -y python3-setuptools
sudo apt-get install -y python3-sphinx
sudo apt-get install -y python3-tk
sudo apt-get install -y python3-tornado
sudo apt-get install -y python3-yaml
sudo apt-get install -y python3-zmq
sudo apt-get install -y python-matplotlib-data

## SoapySDR
sudo apt-get install -y swig
sudo apt-get install -y avahi-daemon
sudo apt-get install -y libavahi-client-dev
sudo apt-get install -y libusb-1.0-0-dev
sudo apt-get install -y python-dev
sudo apt-get install -y python3-dev

# SDR common packages
sudo apt-get install -y gstreamer1.0-libav
sudo apt-get install -y libudev1
sudo apt-get install -y libusb-1.0-0
sudo apt-get install -y libusb-1.0-0-dev
sudo apt-get install -y libusb-dev
sudo apt-get install -y libfftw3-dev

## RTLSDR
sudo pip3 install pyrtlsdr

## HackRF
##

## RX-888 MkII
##

## PlutoSDR
sudo apt-get install -y libaio-dev
sudo apt-get install -y libserialport-dev
sudo apt-get install -y libavahi-client-dev
sudo apt-get install -y libxml2-dev bison flex libcdk5-dev

## LimeSDR
sudo apt-get install -y swig
sudo apt-get install -y libsqlite3-dev
sudo apt-get install -y libi2c-dev
sudo apt-get install -y libwxgtk3.0-dev
sudo apt-get install -y freeglut3-dev
sudo apt-get install -y liboctave-dev
sudo apt-get install -y libfltk1.3-dev

echo -e "${SIGEDGE_BANNER_COLOR}"
echo -e "${SIGEDGE_BANNER_COLOR} ##  Setup Core: Complete"
echo -e "${SIGEDGE_BANNER_RESET}"
