#!/bin/bash

###
### SIGedge
###
### setup_decoders
###
###
### 20260827-2300
###
### Install codecs, demodulators and utilities
###

echo -e "${SIGEDGE_BANNER_COLOR}"
echo -e "${SIGEDGE_BANNER_COLOR} ##"
echo -e "${SIGEDGE_BANNER_COLOR} ##  Setup Decoders"
echo -e "${SIGEDGE_BANNER_COLOR} ##"
echo -e "${SIGEDGE_BANNER_RESET}"

# Install APTdec (NOAA APT)
source $SIGEDGE_PACKAGES/pkg_aptdec install
# Install cm256cc
source $SIGEDGE_PACKAGES/pkg_cm256cc install
# Install mbelib (P25 Phase)
source $SIGEDGE_PACKAGES/pkg_mbelib install
# Install SeriaDV (AMBE3000 chip serial control)
source $SIGEDGE_PACKAGES/pkg_serialdv install
# Install DSDcc (Digital Speech Decoder)
source $SIGEDGE_PACKAGES/pkg_dsdcc install
# Install Codec 2
source $SIGEDGE_PACKAGES/pkg_codec2 install
# Install SGP4
source $SIGEDGE_PACKAGES/pkg_sgp4 install
# Install Direwolf (AFSK APRS)
source $SIGEDGE_PACKAGES/pkg_direwolf install
# Install ggMorse (Morse decode)
source $SIGEDGE_PACKAGES/pkg_ggmorse install
# Install Inmarsatc decoder
source $SIGEDGE_PACKAGES/pkg_inmarsatc install
# Install Dump1090
#source $SIGEDGE_PACKAGES/pkg_dump1090 install
# Install Radiosonde (Atmospheric Telemetry)
#source $SIGEDGE_PACKAGES/pkg_radiosonde install
# Install NRSC5 (HD Radio)
source $SIGEDGE_PACKAGES/pkg_nrsc5 install
# Install Multimon-NG (POCSAG, FSK, AFSK, DTMF, X10)
source $SIGEDGE_PACKAGES/pkg_multimon-ng install

echo -e "${SIGEDGE_BANNER_COLOR}"
echo -e "${SIGEDGE_BANNER_COLOR} ##  Setup Decoders complete"
echo -e "${SIGEDGE_BANNER_RESET}"
