#!/bin/bash

###
### SIGPI
###
### setup_devices
###
###
### 20260117-2300
###
### Devices installed by default include RTLSDR, HackRF, and Ubertooth
### Related software includes SoapySDR, SoapyRemote, SoapyRTLSDR, SoapyHackRF, and GPS
###

echo -e "${SIGPI_BANNER_COLOR}"
echo -e "${SIGPI_BANNER_COLOR} ##"
echo -e "${SIGPI_BANNER_COLOR} ##  Setup Devices"
echo -e "${SIGPI_BANNER_COLOR} ##"
echo -e "${SIGPI_BANNER_RESET}"

# SoapySDR 0.8
echo -e "${SIGPI_BANNER_COLOR}"
echo -e "${SIGPI_BANNER_COLOR} ##  install : SoapySDR "
echo -e "${SIGPI_BANNER_RESET}"

sudo apt-get install -y libusb-1.0-0-dev soapysdr-tools libsoapysdr-dev

echo -e "${SIGPI_BANNER_COLOR}"
echo -e "${SIGPI_BANNER_COLOR} ##  install : SoapySDR - Completed"
echo -e "${SIGPI_BANNER_RESET}"

# SoapySDDC
echo -e "${SIGPI_BANNER_COLOR}"
echo -e "${SIGPI_BANNER_COLOR} ##  install : SoapySDDC "
echo -e "${SIGPI_BANNER_RESET}"

cd $SIGEDGE_SOURCE
git clone https://github.com/renardspark/SDDC_Driver.git
cd $SIGEDGE_SOURCE/SDDC_Driver
cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
cmake --build build -j$(nproc)
sudo cmake --install build
sudo ldconfig

echo -e "${SIGPI_BANNER_COLOR}"
echo -e "${SIGPI_BANNER_COLOR} ##  install : SoapySDDC - Completed"
echo -e "${SIGPI_BANNER_RESET}"

# SoapyRemote
echo -e "${SIGPI_BANNER_COLOR}"
echo -e "${SIGPI_BANNER_COLOR} ##  install : SoapyRemote "
echo -e "${SIGPI_BANNER_RESET}"

sudo apt-get install -y soapyremote-server soapysdr-module-remote

echo -e "${SIGPI_BANNER_COLOR}"
echo -e "${SIGPI_BANNER_COLOR} ##  install : SoapyRemote - Completed"
echo -e "${SIGPI_BANNER_RESET}"

# Install AX.25
source $SIGPI_PACKAGES/pkg_ax25 install

# Install RTLSDR
source $SIGPI_DEVICES/pkg_rtlsdr-v4 install

# Install HackRf
source $SIGPI_DEVICES/pkg_hackrf install

# Install RX-888 MkII
if grep rx-888 "$SIGPI_INSTALLED_DEVICES"; then
    source $SIGPI_DEVICES/pkg_rx888 install
fi

# Install bladeRF
if grep bladerf "$SIGPI_INSTALLED_DEVICES"; then
    source $SIGPI_DEVICES/pkg_bladerf install
fi

# Install Ettus UHD
if grep ettus "$SIGPI_INSTALLED_DEVICES"; then
    source $SIGPI_DEVICES/pkg_ettus install
fi

# Install RigExpert Fobos
if grep fobos "$SIGPI_INSTALLED_DEVICES"; then
    source $SIGPI_DEVICES/pkg_libfobos install
fi

# Install KerberosSDR
if grep kerberos "$SIGPI_INSTALLED_DEVICES"; then
    source $SIGPI_DEVICES/pkg_rtl-sdr-kerberos install
fi

# Install LimeSDR
if grep limesuite "$SIGPI_INSTALLED_DEVICES"; then
    source $SIGPI_DEVICES/pkg_limesuite install
fi

# Install PlutoSDR
if grep plutosdr "$SIGPI_INSTALLED_DEVICES"; then
    source $SIGPI_DEVICES/pkg_plutosdr install
fi

# Install SDRPlay
if grep sdrplay "$SIGPI_INSTALLED_DEVICES"; then
    source $SIGPI_DEVICES/pkg_sdrplay install
fi

# Install Ubertooth One
if grep ubertooth "$SIGPI_INSTALLED_DEVICES"; then
    source $SIGPI_DEVICES/pkg_ubertooth install
fi

echo -e "${SIGPI_BANNER_COLOR}"
echo -e "${SIGPI_BANNER_COLOR} ##"
echo -e "${SIGPI_BANNER_COLOR} ##  Setup Devices: Complete"
echo -e "${SIGPI_BANNER_COLOR} ##"
echo -e "${SIGPI_BANNER_RESET}"