#!/bin/bash

###
### SIGedge_env
###
###  20260827-1700
###

###
### INIT VARIABLES AND DIRECTORIES
###

# SIGpi Directory tree
SIGEDGE_ROOT=$HOME/SIGpi-edge
SIGEDGE_SOURCE=$SIGEDGE_ROOT/source
SIGEDGE_HOME=$SIGEDGE_ROOT
SIGEDGE_ETC=$SIGEDGE_ROOT/etc
SIGEDGE_DEVICES=$SIGEDGE_HOME/devices
SIGEDGE_SCRIPTS=$SIGEDGE_HOME/scripts
SIGEDGE_PACKAGES=$SIGEDGE_HOME/packages
SIGEDGE_DEBS=$SIGEDGE_HOME/debs

# SIGpi Install Support files
SIGEDGE_INSTALLED=$SIGEDGE_ETC/INSTALLED_PKGS
SIGEDGE_PKGLIST=$SIGEDGE_PACKAGES/PACKAGES
SIGEDGE_INSTALLED_DEVICES=$SIGEDGE_ETC/INSTALLED_DEVICES
SIGEDGE_DEVLIST=$SIGEDGE_DEVICES/DEVICES
SIGEDGE_SCREEN_STANDARD=$SIGEDGE_SCRIPTS/screen_standard_setup
SIGEDGE_SCREEN_SERVER=$SIGEDGE_SCRIPTS/screen_server_setup
SIGEDGE_BANNER_COLOR="\e[0;104m\e[K"   # blue
SIGEDGE_BANNER_RESET="\e[0m"

# Detect architecture (x86_64, ARMv8)
SIGEDGE_HWARCH=`lscpu|grep Architecture|awk '{print $2}'`
# Detect Operating system (Debian GNU/Linux 13 (Trixie) or Ubuntu 24.04 LTS)
SIGEDGE_OSNAME=`cat /etc/os-release|grep "PRETTY_NAME"|awk -F'"' '{print $2}'`
# Is Platform good for install- true or false - we start with false
SIGEDGE_CERTIFIED="false"
# What is the IP Address
SIGEDGE_IPADDR=`ip -br address | grep UP | awk '{print $1}'`


